### ISSUE TITLE
Yarn stock

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#11]
## Value Proposition

**As a** Kniter
**I want to** see the stock of my yarns
**so that** I can easily keep track of all my yarns.
​

## Description

​
![US6-yarn-stock-overview](https://github.com/MichanNan/Knittogether/assets/101557182/d522cc9b-cd71-43cd-b8c0-88464b50708a)

## Acceptance Criteria

- [ ] The headline "Yarn Stock" is displayed
- [ ] Each yarn is displayed with its photo, brand, type, color, skein and amount(meter and gramm for single skein).
- [ ] A new icon that leads users to yarn stock page in navigation is displayed.

## Tasks

- [ ] Create branch called `yarn-stock-overview`.
- [ ] Create a mock array of yarn stock in database.
- [ ] Create a component `YarnStockPreview` to render a single yarn.
  - [ ] Each yarn should have a photo, brand, type, color and amount.
- [ ] Create a compoment `YarnStock` to to map and display all yarn.
- [ ] Create a new page `yarn-stock` to render the component `YarnStock`.
- [ ] Create a icon in Navigation that leads to the page `yarn-stock`.

**Comment by CarstenJahnke** [comment]
Very nice Nan! 👍

**Comment by CarstenJahnke** [comment]
update confirmed 😄👍
