### ISSUE TITLE
US8 Add yarn to stock

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#12]
## Value Proposition

**As a** Knitter
**I want to** to be able to add a new yarn
**so that** i can track my new yarn.

## Description
​
![US7-add-yarn-in-stock](https://github.com/MichanNan/Knittogether/assets/101557182/eba2ebcb-eb87-4106-81ac-97b3fae80220)

## Acceptance Criteria

- [ ] Display a "Add" button in the page `yarn-stock`.
- [ ] A form is displayed when the "Add" button is clicked.
- [ ] The form should include a "Create" button and a "Cancel" button.
- [ ] When the "Cancel" button is clicked, navigate back to page `yarn-stock` and cancel the add process.
- [ ] When the "Create" button is clicked, post the new yarn data to database.
- [ ] The input form is displayed accordingly when the "Add" button is clicked.

## Tasks

- [ ] Create branch `add-yarn-in-stock`.
- [ ] Create a component `YarnForm`.
  - [ ] Import the component `Heading` to display the headline "Add Yarn"
  - [ ] Import component `StyledInput` to create the form input fields.
  - [ ] Import component `StyledButton` to create the "Cancel" button and the "Create" button.
- [ ] Create an "Add" button that triggers the component `YarnForm`.
- [ ] Add a event listener to the "Create" button, after the "Create" button is clicked, a new yarn willbe displayed on the page `yarn-stock`.

**Comment by CarstenJahnke** [comment]
Clear and understandable, very good!👍
