### ISSUE TITLE
US9 Edit yarn in stock

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#13]
## Value Proposition

**As a** Knitter
**I want to** to be able to edit my yarn stock
**so that** i can manage my yarn stock.

## Description
![US8-edit-delete-yarn-stock](https://github.com/MichanNan/Knittogether/assets/101557182/c4875f62-cde3-42f3-83af-cfc53b1c9ddf)

## Acceptance Criteria

- [ ] Display a "Delete" button and a "Edit" button for each yarn.
- [ ] Display the component `YarnForm` when the "Edit" button is clicked.
- [ ] After clicking the "Confirm" button in the YarnForm, update the yarn information.
- [ ] A "Cancel" button should navigate the users back to page `yarn-stock`.

## Tasks

- [ ] Create branch `edit-delete-yarn-stock`.
- [ ] Create a "Delete" button and a "Edit" button for each yarn.
- [ ] Create a state variable called `isEdit` with an initial value of "false". This state variable will control whether the YarnForm component is triggered or not. Set the state `isEdit` to "true" when the "Edit" button is clicked.
- [ ] Add a event listener to the "Cancel" button that navigats users back to page `yarn-stock`.
- [ ] Add a event listener to the "Delete" button that deletes the corresponding yarn.
- [ ] Implement the YarnForm component to allow updating the yarn information when the "Confirm" button is clicked.

**Comment by CarstenJahnke** [comment]
Update confirmed 👍 👍
