### ISSUE TITLE
US6 Add yarn in the project adding page

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#14]
## Value Proposition

**As a** Knitter
**I want to** to be able to add more yarns
**so that** I can record my project detailed.

## Description
​
![US6-add-yarn-in-add-project-page](https://github.com/MichanNan/Knittogether/assets/101557182/d1aca4e9-ed36-4b71-b7d3-215d0ca4f9da)

## Acceptance Criteria

- [ ] An "Add" button and "Delete" button are displayed to each yarn.
- [ ] Allow users to manage yarn of the project.

## Tasks

- [ ] Create branch `add-yarn-in-add-project-page`.
- [ ] Import component `StyledButton` to render "Add" button and "Delete" button to each yarn
- [ ] Add an event listener to the "Add" button so that when it is clicked, a new yarn input field is added.
- [ ] Add an event listener to the "Delete" button so that when it is clicked, the corresponding yarn input field is deleted.

**Comment by CarstenJahnke** [comment]
LGTM Nan ☺️👍
