### ISSUE TITLE
US10 Upload project image

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#18]
## Value Proposition

**As a** Knitter
**I want to** to be able to upload the image of my project
**so that** i can have a better overview of my project.

## Description
​
![US10-upload-project-image](https://github.com/MichanNan/Knittogether/assets/101557182/fd1a609d-3bbf-4f54-bef4-334c14ec457a)

## Acceptance Criteria

- [ ] Display a "Add Image" button.
- [ ] Display image after the user uploaded a file.
- [ ] Allow the user to change image of a existed project.

## Tasks

- [ ] Create branch `upload-project-image`.
- [ ] Create a component `Upload`.
- [ ] Render the component `Upload` in `ProjectForm`.
- [ ] Create a state `imageUrl` to save the uploaded image url.
- [ ] Pass the image url to the function `handleProjectRestructure` to create the new project.

**Comment by MariaRiosNavarro** [comment]
Short and clear, fantastic, nothing to complain about.🚀
