### ISSUE TITLE
Project detail

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/knittogether#2]
## Value Proposition

**As a** Kniter
**I want to** see the detail of my project
**so that** I can easily keep track of the details of my project.
​

## Description

![US2-project-detail-page](https://github.com/MichanNan/knittogether/assets/101557182/28d00c46-d053-42c9-9c2e-a4dce05cdaca)

​

## Acceptance Criteria

- [ ] Clicking on a project from the list displays the detail page.
- [ ] The project title is displayed.
- [ ] Clicking on the back button takes the user back to the projects list page.
- [ ] The project status and happiness are both displayed.
- [ ] The project photo is displayed.
- [ ] All project details information is displayed.
- [ ] Edit button and delete button are displayed.
      ​

## Tasks

- [ ] Create branch `project-detail`.
- [ ] Create an event listener on the project list to display the project detail page when a project is clicked.
- [ ] Create a detail page `/project/[id]`that renders according to the project id.
- [ ] Create a back button that takes the user back to the projects list page when clicked.
- [ ] Create a component `ProjectDetail`.
- [ ] Create an edit button without any functionality at present.
- [ ] Create a delete button that deletes the project when clicked.
- [ ] Write test.

**Comment by MariaRiosNavarro** [comment]
You have a mini error in: „The form section details are displyed“ , you are missing an „a“

It's a lot of work for a user story, but I think you can do it and it's also just a Task. I think that by correcting that little thing, it would be correct from my point of view.

**Comment by MichanNan** [comment]
> You have a mini error in: „The form section details are displyed“ , you are missing an „a“
> 
> It's a lot of work for a user story, but I think you can do it and it's also just a Task. I think that by correcting that little thing, it would be correct from my point of view.

Thanks Maria!
