### ISSUE TITLE
US11 needle stock overview

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#21]
## Value Proposition

**As a** Knitter
**I want to** see the stock of my needles
**so that** I can easily keep track of all my needles.
​

## Description

​
![US11-neddle-stock-overview](https://github.com/MichanNan/Knittogether/assets/101557182/6a637440-70ff-45cb-a514-86fef4f63951)

## Acceptance Criteria

- [ ] A category is displayed, switch to each category shows corresponding content.
- [ ] In Needle stock all needles are displayed.
- [ ] Each needle is displayed with its size, length and amount.

## Tasks

- [ ] Create branch called `needle-stock-overview`.
- [ ] Create a mock array of needle stock in database.
- [ ] Create a component `NeedleStockItem` to render a single needle.
  - [ ] Each needle should have size, length and amount.
- [ ] Create a component `NeedleStock` to map and display all needles.
- [ ] Create a component `StockCategories` to show corresponding content when a category is clicked.
- [ ] Render the component `StockCategories` in the page `stock`.

**Comment by CarstenJahnke** [comment]
LGTM Nan 🙌
