### ISSUE TITLE
US12 add needle to stock

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#22]
## Value Proposition

**As a** Knitter
**I want to** to be able to add a new needle
**so that** i can track my new needle.

## Description

​
![US12-needle-add](https://github.com/MichanNan/Knittogether/assets/101557182/7892ee33-2a7a-46ef-8331-c32f463ec889)

## Acceptance Criteria

- [ ] Display a "Add" button.
- [ ] The form `Add needle` is displayed when the "Add" button is clicked.
- [ ] The form should include a "Create" button and a "Cancel" button.
- [ ] When the "Cancel" button is clicked, navigate back to page `stock` and cancel the add process.
- [ ] When the "Create" button is clicked, post the new needle data to database.

## Tasks

- [ ] Create branch `add-needle-in-stock`.
- [ ] Create a component `NeedleForm`.
  - [ ] Import the component `Heading` to display the headline "Add Needle"
  - [ ] Import component `StyledInput` to create the form input fields.
  - [ ] Import component `StyledButton` to create the "Cancel" button and the "Create" button.
- [ ] Add a event listener to the "Create" button, after the "Create" button is clicked, a new needle will be displayed on the page `yarn-stock`.

**Comment by CarstenJahnke** [comment]
LGTM Nan 🙌
