### ISSUE TITLE
US13 edit needle in stock

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#23]
## Value Proposition

**As a** Knitter
**I want to** to be able to edit my needle stock
**so that** i can manage my needle stock.

## Description

![US13-needle-edit](https://github.com/MichanNan/Knittogether/assets/101557182/b13da769-c8c2-464a-ae13-0bc7139353cc)

​

## Acceptance Criteria

- [ ] Display a "Delete" button and a "Edit" button for each needle.
- [ ] Display the component `NeedleForm` when the "Edit" button is clicked.
- [ ] After clicking the "Confirm" button in the NeedleForm, update the needle information.
- [ ] A "Cancel" button should cancel the edit process.
- [ ] The needle should be delete from the database after clicking the button "Delete".

## Tasks

- [ ] Create branch `edit-delete-needle-stock`.
- [ ] Create a "Delete" button and a "Edit" button for each needle.
- [ ] Create a state variable called `isEdit` with an initial value of "false". This state variable will control whether the NeedleForm component is triggered or not. Set the state `isEdit` to "true" when the "Edit" button is clicked.
- [ ] Add a event listener to the "Cancel" button that cancels editing.
- [ ] Add a event listener to the "Delete" button that deletes the corresponding needle.
- [ ] Implement the NeedleForm component to allow updating the needle information when the "Confirm" button is clicked.
