### ISSUE TITLE
US14 add home page

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#27]
## Value Proposition

**As a** Knitter
**I want to** have a summary on the home page.
**so that** i can have a overview of my projects.

## Description

​
![US14-home-page](https://github.com/MichanNan/Knittogether/assets/101557182/658c99dc-61be-4e97-8661-0d0ee9d58200)

## Acceptance Criteria

- [ ] A heading with the name of the app is displayed.
- [ ] A pie chart that shows the overview of all projects is displayed.
- [ ] A list of active projects is displayed.

## Tasks

- [ ] Create branch `add-home-page`.
- [ ] Change the original Page `index` to `project` and create a new page `index` that render the summary of all projects.
- [ ] Create a pie chart.
- [ ] Create the list of active projects that is horizontally scrollable.
- [ ] Add `home` to the Navigation that leads the user to home page.

**Comment by MariaRiosNavarro** [comment]
Perfect 🙌🏾
