### ISSUE TITLE
US15 search pattern in open api

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#29]
## Value Proposition

**As a** Knitter
**I want to** be able to search pattern from ravelry.
**so that** I can find inspiration for my knitting projects.

## Description
​
![US15-search-pattern-from-api](https://github.com/MichanNan/Knittogether/assets/101557182/ff779edc-0223-4c12-9c68-feec19e797ef)

## Acceptance Criteria

- [ ] A search bar is displayed.
- [ ] Corresponding content is displayed after the search button is clicked.

## Tasks

- [ ] Create branch `search-pattern-from-api`.
- [ ] Create a page `pattern`.
- [ ] Add new Icon `pattern` to  component `Navigation` and link to the page `pattern`.
- [ ] Utilize api from Ravelry to search for patterns.

**Comment by CarstenJahnke** [comment]
LGTM 🤗
