### ISSUE TITLE
Add new project

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/knittogether#3]
## Value Proposition

**As a** Kniter
**I want to** to be able to add a new knitting project.
**so that** i can share and track my new projects.

## Description

​
![US3-edit-project](https://github.com/MichanNan/knittogether/assets/101557182/922ab63f-e498-47b8-80e7-dd7a588c4b9c)

## Acceptance Criteria

- [ ] Display a pop-up when the "Add" button in the project list is clicked.
- [ ] Display an input field in the pop-up for the user to add the project title.
- [ ] Display a cancel button and a create button in the pop-up.
- [ ] When the "Create" button is clicked, navigate to the edit project detail page.
- [ ] When the "Edit" button is clicked for the project detail and yarn information, render the input field.
- [ ] Allow the user to add more than one yarn.
- [ ] Allow the user to upload a PDF file as a pattern.
- [ ] Display an input field for adding notes.
- [ ] Display a delete button and a save button.

## Tasks

- [ ] Create branch `edit-project-detail`.
- [ ] Create a component `PreAddProject`.
- [ ] Create an event listener to the "Add" button on the project list page. When the button is clicked, render the component `PreAddProject`.
- [ ] Create a headline to display the project title, which will come from the input field in the component `PreAddProject`
- [ ] Create a component `EditProjectDetail` contains a form element.
   - [ ] Create respectively a dropdown for the project status and happiness.
   - [ ] Create seperatly a state `isEdit` for the detail information and yarn information to dynamically render the input fields. When the user clicks on "Add," render the input fields.
   - [ ] Create a state for the entire detail page to determine whether the page is editable.
   - [ ] Add an event listener to the edit button on the project detail page that toggles the status of the entire detail page. When the user clicks "Edit" on the detail page, render the component `EditProjectDetail` and hide the component `ProjectDetail`.
   - [ ] Create the backend API for create a project.
   - [ ] Create an event listener for the "Save" button. When the form is submitted, the data will be stored in the database.
