### ISSUE TITLE
US16 authentication

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#32]
## Value Proposition

**As a** Knitter
**I want to** be able to login to the app.
**so that** I can find manage my own projects.

## Description
​
![US16-authentication](https://github.com/MichanNan/Knittogether/assets/101557182/2c42bd31-112b-4012-8cb3-1398ed70903c)

## Acceptance Criteria

- [ ] A login page is displayed when the user first opens the app.
- [ ] Navigate the user to the home page when the user is authorized.
- [ ] Allow the user to register an account by clicking on "create new account."
- [ ] Navigate the user to the login page after registering.

## Tasks

- [ ] Create branch `authentication`.
- [ ] Create a page `login`.
- [ ] Create the api `login` to authorize the user.
- [ ] Create a page `register`.
- [ ] Create the api `register` to add user information to data base.
- [ ] Rebuild the project schema and add an author to each project in oder to show the project according to the different users.

**Comment by Danielschuetzle** [comment]
LGTM
