### ISSUE TITLE
US17 community

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#34]
## Value Proposition

**As a** Knitter
**I want to** be able to post my project to community
**so that** I can share my project with everyone.

## Description
​
![US17-community](https://github.com/MichanNan/Knittogether/assets/101557182/7176ee42-4260-4003-9cc3-d9765baf5f43)

## Acceptance Criteria

- [ ] A share button is displayed on the project detail page.
- [ ] The project will post to community when clicking the share button.
- [ ] Allow the user to see all the projects that are posted to community.
- [ ] The name and author of each project are displayed.
- [ ] A like icon is displayed to each project.
- [ ] A detail page with comment is displayed when clicking on the post.
- [ ] Allow the user add new comment to the post.

## Tasks

- [ ] Create branch `community`.
- [ ] Add a "Post" button to the project detail page.
- [ ] Create a page `community` to display all the projects posted..
- [ ] Create an api endpoint `community` to send post data to the database.
- [ ] Create the schema `post`.
- [ ] Create the schema `comment`.
- [ ] Create a detail page to each post, displaying all comments of the post.
- [ ] Create a comment form on the detail page to allow users to add new comments to the post.

**Comment by MariaRiosNavarro** [comment]
Wow the scope is pretty big, but I've told you many times, if anyone can do it, it's you. On the one hand you could put the comments in another US. But then it would be too small and meaningless. I think that's fine and it keeps the community together. 🚀
