### ISSUE TITLE
US4 Add search bar

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#4]
## Value Proposition

**As a** Knitter
**I want to** to be able to search for my projects
**so that** I can quickly find specific projects.

## Description

​
![US4-add-searchbar](https://github.com/MichanNan/Knittogether/assets/101557182/9808e2b3-b004-4567-b569-31ccc320766a)

## Acceptance Criteria

- [ ] A search bar is displayed.
- [ ] User can search project according to name.
- [ ] corresponding projects are displayed when the user click on search.

## Tasks

- [ ] Create branch `add-searchbar`.
- [ ] Create a component `SearchBar`.
- [ ] Create an event listener to the "Search" button so that when it is clicked, the corresponding projects are displayed.

**Comment by MariaRiosNavarro** [comment]
LGFM 🚀
