### ISSUE TITLE
US5 Project detail page

### ISSUE THREAD

**Issue by MichanNan** [MichanNan/Knittogether#5]
## Value Proposition

**As a** Kniter
**I want to** see the detail of my project
**so that** I can easily keep track of the details of my project.
​

## Description

![US5-project-detail-page](https://github.com/MichanNan/Knittogether/assets/101557182/7129dcc6-b30c-4a8a-8045-ba483dd4ef33)

## Acceptance Criteria

- [ ] Clicking on a project from the list displays the corresponding detail page.
- [ ] The project title is displayed.
- [ ] Clicking on the back button takes the user back to the projects list page.
- [ ] The project status and happiness are both displayed.
- [ ] The project photo is displayed.
- [ ] All project details information is displayed.
- [ ] Project pattern is displayed.
- [ ] Project yarn is displayed.
- [ ] Edit button and delete button are displayed.
      ​

## Tasks

- [ ] Create branch `project-detail`.
- [ ] Create an event listener on the project list to display the project detail page when a project is clicked.
- [ ] Create a component `ProjectDetail`.
  - [ ]Create a back button that takes the user back to the projects list page when clicked.
  - [ ] Create a headline.
  - [ ] Create a section of project details.
  - [ ] Create a section of project Pattern.
  - [ ] Create a section of project Yarn.
  - [ ] Create a section of project note.
  - [ ] Create an edit button
  - [ ] Create a delete button that deletes the project when clicked.
- [ ] Create a detail page `/project/[id]`that renders the component `ProjectDetail` according to the project id.

**Comment by MariaRiosNavarro** [comment]
wow Really detailed Tasks , LGFM 🚀
